version: '3.8'

services:
  backend:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/fast_api_mvc

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
