name: CI/CD

on:
  pull_request:
    branches: [ "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t vyacheslavshrot/fast_api_mvc:latest .

      - name: Push Docker image to Docker Hub
        run: docker push vyacheslavshrot/fast_api_mvc:latest